### ISSUE TITLE
dynamic year for about page

### ISSUE THREAD

**Issue by abotzki** [elixir-europe-training/ELIXIR-Training-SPLASH#126]
[pages/about/about.md](https://github.com/elixir-europe-training/ELIXIR-Training-SPLASH/pull/123/files/eec21b753e3b4a032a5a0f6b0f9de588ce862ab6#diff-72f328d66d88f2df6b14d9e537d7f8492195f5a51511d9230c9f2b8661a8601b)

**Comment by GeertvanGeest** [comment]
You mean in the citation? I.e.:

```
ELIXIR SPLASH Pushing the boundaries of training development (2023)
```
