### ISSUE TITLE
define editoral board and editorial process

### ISSUE THREAD

**Issue by abotzki** [elixir-europe-training/ELIXIR-Training-SPLASH#139]
define editoral board and edit process

- [x] review https://github.com/elixir-europe-training/ELIXIR-Training-SPLASH/blob/main/pages/about/editorial_board.md
- [x] review https://github.com/elixir-europe-training/ELIXIR-Training-SPLASH/blob/main/pages/contribute/editorial_board_guide.md
- [x] review https://github.com/elixir-europe-training/ELIXIR-Training-SPLASH/blob/main/pages/contribute/editors_checklist.md
- [x] review https://github.com/elixir-europe-training/ELIXIR-Training-SPLASH/blob/main/pages/contribute/how_to_contribute.md
- [x] review https://github.com/elixir-europe-training/ELIXIR-Training-SPLASH/blob/main/pages/about/contributors.md

**Comment by mihai-sysbio** [comment]
@abotzki it would have been easier to review and suggest changes via a pull request, but I see these are all in the `main` branch.

**Comment by abotzki** [comment]
Thanks for the feedback - please check the PR https://github.com/elixir-europe-training/ELIXIR-Training-SPLASH/pull/143 to give dedicated feedback!

**Comment by elinkronander** [comment]
I have reviewed the above pages and made some small changes and added comments/suggestions in 2 Draft PRs #148 and #147

**Comment by abotzki** [comment]
Thank you very much for your efforts - has been addressed by #161

**Comment by abotzki** [comment]
and by #174
