### ISSUE TITLE
Issue on page: ELIXIR-GOBLET Train the Trainer

### ISSUE THREAD

**Issue by zlitou** [elixir-europe-training/ELIXIR-Training-SPLASH#142]
I would like to report an issue on the ELIXIR-GOBLET Train the Trainer page at `/train-the-trainer`. Description of the issue:
Change resourceUrl from   https://elixir-europe.org/   to    https://elixir-europe.org/platforms/training/train-the-trainer

**Comment by abotzki** [comment]
#142 closed as now merged #150
