### ISSUE TITLE
feat: extend editorial guidelines with recommendations

### ISSUE THREAD

**Issue by abotzki** [elixir-europe-training/ELIXIR-Training-SPLASH#144]
@mihai-sysbio my expectation of the editorial guidelines were that these would also include some practical instructions/recommendations, i.e., follow British English spelling, prefer concise wording and an academic style.

**Comment by mihai-sysbio** [comment]
The above is coming from https://github.com/elixir-europe-training/ELIXIR-Training-SPLASH/pull/143#issuecomment-2518242245

**Comment by abotzki** [comment]
Has been addressed by #161 - see link https://elixir-europe-training.github.io/ELIXIR-Training-SPLASH/style_guide#general-style-and-tone
