### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by spiwokv** [elixir-europe-training/ELIXIR-Training-SPLASH#162]
### https://elixir-europe-training.github.io/ELIXIR-Training-SPLASH/tess

a big link to TeSS missing https://tess.elixir-europe.org/

### https://elixir-europe-training.github.io/ELIXIR-Training-SPLASH/tmd

a big link ot TMD missing https://training-metrics-dev.elixir-europe.org/

### https://elixir-europe-training.github.io/ELIXIR-Training-SPLASH/learning-paths

link https://elixir-europe.org/focus-groups/learning-paths could be added

### https://elixir-europe-training.github.io/ELIXIR-Training-SPLASH/elearning

is it appropriate to add https://elixir.mf.uni-lj.si/ or another service is used?

### https://elixir-europe-training.github.io/ELIXIR-Training-SPLASH/fair-training-handbook

is it a good idea to add this link
https://elixir-europe-training.github.io/ELIXIR-TrP-FAIR-training-handbook/#
or it is going to be added after migration to elixir-europe.org?

**Comment by abotzki** [comment]
- for elearning no link will be added, the gdoc link should be replaced by the Zenodo link
