### ISSUE TITLE
correct numbers on the main page to align with ELIXIR Europe website

### ISSUE THREAD

**Issue by abotzki** [elixir-europe-training/ELIXIR-Training-SPLASH#168]

**Comment by abotzki** [comment]
Since 2015
1,700+
training events
38,700+
people trained
99+ countries
4,700+

**Comment by olisand** [comment]
Since the numbers with + signs are not accepted by Jekyl, I suggest we leave the existing numbers that are higher than those on the ELIXIR web site and just update countries to 99 (or 100?).

**Comment by abotzki** [comment]
solved by #170
