### ISSUE TITLE
Welcome page changes

### ISSUE THREAD

**Issue by bpiereck** [elixir-europe-training/ELIXIR-Training-SPLASH#58]
- [x] Banner msg: pushing the boundaries of training development
- [x] Banner should be full width
- [x] wording "Training Life Cycle" to add above or bellow (image should be untouched!)
- [x] One gliph per resource according to https://vib.be/en/technologies/core-facilities (re-use)
- [x] The SPLASH in number to be updated: Trainers, Countries, Training Events, Trainees

**Comment by ahornos** [comment]
Is this issue still open?
In that case, what number should the home page show?

**Comment by mihai-sysbio** [comment]
> Is this issue still open?

yes I think so

> In that case, what number should the home page show?

The best source for these numbers is the [TMD](https://tmd.elixir-europe.org). Perhaps some of these might be fetched via API? There is a Slack channel `#tmd` to get in touch with the Nodes powering the service.

**Comment by abotzki** [comment]
solved by #173
